CREATE TABLE IF NOT EXISTS user_notification_settings (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    app_enabled BOOLEAN NOT NULL DEFAULT true,
    email_enabled BOOLEAN NOT NULL DEFAULT true,
    app_moderation BOOLEAN NOT NULL DEFAULT true,
    email_moderation BOOLEAN NOT NULL DEFAULT true,
    app_booking_received BOOLEAN NOT NULL DEFAULT true,
    email_booking_received BOOLEAN NOT NULL DEFAULT true,
    app_point_assigned BOOLEAN NOT NULL DEFAULT true,
    email_point_assigned BOOLEAN NOT NULL DEFAULT true,
    app_material_deposited BOOLEAN NOT NULL DEFAULT true,
    email_material_deposited BOOLEAN NOT NULL DEFAULT true,
    app_material_recovered BOOLEAN NOT NULL DEFAULT true,
    email_material_recovered BOOLEAN NOT NULL DEFAULT true,
    app_rating_received BOOLEAN NOT NULL DEFAULT true,
    email_rating_received BOOLEAN NOT NULL DEFAULT true,
    app_booking_cancelled BOOLEAN NOT NULL DEFAULT true,
    email_booking_cancelled BOOLEAN NOT NULL DEFAULT true,
    app_booking_expired BOOLEAN NOT NULL DEFAULT true,
    email_booking_expired BOOLEAN NOT NULL DEFAULT true,
    app_deposit_reminder BOOLEAN NOT NULL DEFAULT true,
    email_deposit_reminder BOOLEAN NOT NULL DEFAULT true,
    display_mode TEXT NOT NULL DEFAULT 'light',
    language TEXT NOT NULL DEFAULT 'fr',
    map_type TEXT NOT NULL DEFAULT 'plan',
    show_phone_publicly BOOLEAN NOT NULL DEFAULT false,
    show_email_publicly BOOLEAN NOT NULL DEFAULT false
);
